font_family	monospace
bold_font	auto
italic_font	auto
bold_italic_font	auto
font_size 15

foreground #F8F8F8
background #181818

selection_foreground #000000
selection_background #D8D8D8

color0 #181818
color8 #6B6B6B

color1 #AC4242
color9 #C55555

color2 #90A959
color10 #AAC474

color3 #F4BF75
color11 #FECA88

color4 #6A9FB5
color12 #82B8C8

color5 #AA759F
color13 #C28CB8

color6 #75B5AA
color14 #93D3C3

color7 #D8D8D8
color15 #F8F8F8

shell fish
editor vim
